Test `socket_passcred` only for Unix domain sockets
Since Linux 6.16, `SO_PASSCRED` is allowed only for `AF_UNIX`, `AF_NETLINK` and
`AF_BLUETOOTH` sockets. The tests used to get/set this option for IP sockets,
which doesn't work with new kernels, so make the tests use a Unix domain socket
instead.

On new kernels, the tests fail with:

```
---- sockopt::test_sockopts_ipv6 stdout ----

thread 'sockopt::test_sockopts_ipv6' panicked at tests/net/sockopt.rs:44:42:
called `Result::unwrap()` on an `Err` value: Os { code: 95, kind: Unsupported, message: "Operation not supported" }

---- sockopt::test_sockopts_ipv4 stdout ----

thread 'sockopt::test_sockopts_ipv4' panicked at tests/net/sockopt.rs:44:42:
called `Result::unwrap()` on an `Err` value: Os { code: 95, kind: Unsupported, message: "Operation not supported" }
```

The restriction was introduced to Linux in this commit:

https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=7d8d93fdde50b86bbbf46a203c368ed320e729ab